let language = {
    "class": {
        "fr": {
            "txt12": "AppLauncherMAUI (nom à changer...)",
        },
        "en": {
            "txt12": "AppLauncherMAUI (will change later...)",
        }
    },
    "id": {
        "fr": {
            "lang": "EN",
            "txt1":"Développeur full-stack",
            "txt2": "Et bien plus...",
            "txt3": "Curieux et motivé, j'aime concevoir des applications robustes et scalables en alliant performance et simplicité. Fort d'une solide expérience dans le développement web, notamment avec PHP et NodeJS avec des frameworks et librairies comme Laravel et React. J'explore aussi avec enthousiasme le C#, MAUI et Godot sur mon temps libre.",
            "txt4": "Au-delà des languages, ce qui me passionne est l'architecture logicielle : penser une application pour qu'elle évolue sereinement tout en faisant qu'elle reste maintenable et efficace. Si j'apprécie la puissance des frameworks et des librairies, je valorise aussi la liberté de coder sans, afin de mieux comprendre les défis et avantages de chaque projet.",
            "txt5": "Je suis toujours à la recherche de nouveaux challenges, prêt à échanger sur des projets ambitieux et innovants ! 🚀",
            "txt6": "Contactez-moi :",
            "txt7": "Mes projets",
            "txt8": "Quel design INCROYABLE",
            "txt9": "Favs, dans son état actuel, permet de créer des raccourcis rapidement sur votre navigateur et de personnaliser leur apparence et position. L'objectif final est d'en faire une véritable page d'accueil pour n'importe quel navigateur.",
            "txt10": "Favs a été réalisé en HTML, CSS et Javascript natif grâce à l'API IndexedDB me permettant de stocker de petites quantités de données directement dans le navigateur.",
            "txt11": "Cela a demandé un travail réfléchi sur la manière de structurer les données et sur la manière de faire fonctionner un tel projet. Et tout ça, disponible sur <a href=\"https://github.com/Latonal/Favs\">GitHub</a>.",
            "txt13": "Encore en cours de dév'!",
            "txt14": "Ce projet a pour but de fournir une GUI claire au téléchargement d'applications externes, et d'offrir une application simple à modifier à tout type de développeur et de besoin.",
            "txt15": "Réalisé avec C#, le framework MAUI et l'architecture MVVM. Disponible sur <a href=\"https://github.com/Latonal/AppLauncherMAUI\">Github</a>.",
            "txt16": "Mes expériences",
            "txt17": "Ils m'ont déjà choisi",
            "txt18": "2023 - Maintenant : Freelance",
            "txt19": "Période de freelance m'ayant permi de travailler dans plusieurs secteurs et d'être constamment confronté à de nouveaux challenges",
            "txt20": "CDI chez Fortil afin d'intégrer les équipes de Natixis",
            "txt21": "Développeur full-stack sur les technologies PHP, Laravel, NodeJS et React en étant aussi Chef de Projet",
            "txt22": "2021 : Diplômé d'un Master",
            "txt23": "Manageur de l'économie numérique spécialité technologies et développement à la Web School Factory",
            "txt24": "Stage suivi d'une période de freelance en tant que développeur front sur les technologies PHP et Wordpress",
            "txt25": "2018 : Certification Opquast",
            "txt26": "Maîtrise de la qualité en projet Web",
        },
        "en": {
            "lang": "FR",
            "txt1":"Full-stack developer",
            "txt2": "And more...",
            "txt3": "Curious and motivated, I like to design robust and scalable applications by combining performance and simplicity. With a solid experience in web development, notably with PHP and NodeJS with frameworks and libraries likes Laravel and React. I also enthusiastically explore C#, MAUI And Godot in my free time.",
            "txt4": "Beyond languages, what fascinates me is software architecture: designing an application so that it evolves smoothly while ensuring that it remains maintainable and efficient. While I appreciate the power of frameworks and libraries, I also value the freedom to code without them, in order to better understand the challenges and benefits of each project.",
            "txt5": "I am always looking for new challenges, ready to discuss ambitious and innovative projects! 🚀",
            "txt6": "Contact me:",
            "txt7": "My projects",
            "txt8": "What an INCREDIBLE design",
            "txt9": "Favs, in its current state, allows you to quickly create shortcuts on your browser and customize their appearance and position. The ultimate goal is to make it a real home page for any browser.",
            "txt10": "Favs was built in native HTML, CSS and Javascript using the IndexedDB API allowing me to store small amounts of data directly in the browser.",
            "txt11": "This required some thoughtful work on how to structure the data and how to make such a project work. And it's all available on <a href=\"https://github.com/Latonal/Favs\">GitHub</a>.",
            "txt13": "Still working on it!",
            "txt14": "This project aims to provide a clear GUI for downloading external applications, and to offer an easy-to-modify application for any type of developer and need.",
            "txt15": "Built with C#, MAUI framework and MVVM architecture. Available on <a href=\"https://github.com/Latonal/AppLauncherMAUI\">Github</a>.",
            "txt16": "My experiences",
            "txt17": "They already chose me",
            "txt18": "2023 - Now : Freelance",
            "txt19": "Freelance period allowing me to work in several sectors and to be constantly confronted with new challenges",
            "txt20": "Permanent contract at Fortil to join the Natixis teams",
            "txt21": "Full-stack developer on PHP, Laravel, NodeJS and React technologies while also being Project Manager",
            "txt22": "2021: Master's degree graduate",
            "txt23": "Digital economy manager specializing in technologies and development at the Web School Factory",
            "txt24": "Internship followed by a freelance period as a front-end developer on PHP and Wordpress technologies",
            "txt25": "2018: Opquast Certification",
            "txt26": "Quality control in web projects",
        }
    }
}