let language = {
    "version":0.1,
    "unique": {
        "fr": {
            "fr":"Français",
            "en":"Anglais",
            "top-ref":"À propos",
            "projects-ref":"Mes projets",
            "contact-me-ref":"Contact",
            "title":"Développeur full stack",
            "art1":"<h2>À propos de moi</h2><div class='group'><div><p>Développeur web cherchant à se diversifier sur différent sujets, aussi bien en développement qu'en d'autres corps de métier y étant lié.</p><p>Diplômé d'un Master en 2021, j'ai déjà eu à travailler entre autres avec Natixis, Asmodee et la RATP.</p><p>Mon école a eu pour avantage de nous introduire à plusieurs expertises en dehors du développement et aussi de nous permettre de nous familiariser rapidement au travail en groupe.</p></div><img src='content/img/RESMI_Nicolas.jpg' alt='Photo de Nicolas Resmi' class='photo'></div><div class='group' id='natixis'><img src='content/img/natixis.png' class='outline' alt='logo de Natixis'><div><p>Agence collaborative avec trois autres camarades, notre mission était de simplifier la création de bilans en créant une plateforme sécurisée en interne pour permettre aux divers acteurs de déposer leurs résultats.</p></div></div><div class='group'><img src='content/img/asmodee.png' alt='logo de Asmodee'><div><p>Projet durant lequel nous avons eu à organiser des playtest pour récupérer les retours de joueurs par rapport aux tendances actuelles dans le secteur du jeu et du jeu de société. Nous avons aussi eu à essayer l'alpha d'un projet en cours.</p></div></div><div class='group'><img src='content/img/ratp.svg' alt='logo de la RATP'><div><p>Projet dans lequel nous avons eu à imaginer plusieurs services pour les utilisateurs de la RATP, ainsi qu'à créer un prototype fonctionnel, entraînant la création d'un site utilisant une base de données utilisateurs anonymisée ainsi que des API RATP disponibles en ligne pour la création de cartes intéractives.</p></div></div>",
            "art2":"<h2>Mes principes</h2><p>Chaque bits compte, je cherche à optimiser autant que mes connaissances le permette afin de rendre l'expérience des utilisateurs la meilleure possible, et vise à m'améliorer toujours plus sur ce point.</p><p>L'accessibilité est aussi un point important qui se développe de plus en plus et sur lequel je vise à donner plus d'efforts.</p><p>Je cherche à diversifier mes talents, autant pour en apprendre plus mais aussi afin de comprendre les besoins de chacun et ainsi mieux communiquer.</p>",
            "art3":"<h2>Mes langages du coeurs</h2><div class='group'><img src='content/img/html5.svg' alt='html5 logo'><img src='content/img/css.svg' alt='css logo'><p>Impossible de passer à côté, pour le développement web, bien que les deux semblent simple en surface, il y a énormément à couvrir que de simplement faire une jolie page. Le référencement et l'optimisation commence par là.</p></div><div class='group'><p>Aussi bien en vanilla, qu'avec des frameworks ou en NodeJS, je saurais m'adapter et ainsi répondre à vos demandes.</p><img src='content/img/js.svg' alt='javascript logo'></div><div class='group'><img src='content/img/php.svg' alt='php logo'><p>En tant que langage serveur avec Wordpress ou autre, PHP ne me fait pas peur.</p></div><div class='group'><p>Passionné de jeux vidéo, j'ai pour objectif de créer mes propres projets et ait déjà acquis nombreuses connaissances pour espérer y parvenir.</p><img src='content/img/csharp.svg' alt='c-sharp logo'><img src='content/img/unity.svg' alt='unity logo' class='unity-logo outline'></div><div class='group' id='projects'><p>+</p><p>Et bien plus afin de répondre à vos besoins, apprendre ne me fais pas peur et est d'ailleurs une compétence. J'ai déjà eu à travailler sur des projets en Go, ASP.Net, Visual Basic, Basic, Python, et bien d'autres langages.</p></div>",
            "my-projects":"Mes projets",
            "ongoing-text":"En cours",
            "finished-text":"Finis",
            "contact-me":"<h2>Contactez moi !</h2><div class='group'><div><p>Envie de simplement dire \"Bonjour\" ou de m'embaucher ? N'hésitez pas à me contacter !</p><p>Vous pouvez m'envoyer un mail à mon adresse : <a href='mailto:nresmi.pro@gmail.com'>nresmi.pro@gmail.com</a></p></div></div>"
        },
        "en": {
            "fr":"French",
            "en":"English",
            "top-ref":"About me",
            "projects-ref":"My projects",
            "contact-me-ref":"Contact",
            "title":"Full-stack developer",
            "art1":"<h2>About me</h2><div class='group'><div><p>Web developer seeking to diversify on different subjects, both in development and in other related projects.</p><p>Graduated with a Master's degree in 2021, I already had to work with Natixis, Asmodee and RATP, among others.</p><p>My school had the advantage of introducing us to several areas of expertise outside of development and also allowing us to quickly familiarize ourselves with group work.</p></div><img src='content/img/RESMI_Nicolas.jpg' alt='Photo de Nicolas Resmi' class='photo'></div><div class='group' id='natixis'><img src='content/img/natixis.png' class='outline' alt='logo de Natixis'><div><p>Collaborative agency with three other friends, our mission was to simplify the creation of sensitive reports by creating a secure platform internally to allow the various actors to submit their results.</p></div></div><div class='group'><img src='content/img/asmodee.png' alt='logo de Asmodee'><div><p>Project during which we had to organize playtests to collect players' feedbacks on current trends in the game and board game sector. We also participated in the alpha of a work in-progress project.</p></div></div><div class='group'><img src='content/img/ratp.svg' alt='logo de la RATP'><div><p>Project in which we had to imagine several services for RATP users, as well as to create functional prototypes, resulting in the creation of a site using an anonymized user database as well as RATP's APIs available online for the creation of our services and interactive maps.</p></div></div>",
            "art2":"<h2>My convictions</h2><p>Every bits count, I try to optimize as much as my knowledge allows in order to make the user experience the best possible, and aim to always improve myself on this point.</p><p>Accessibility is also an important point that is developing more and more and on which I aim to give more effort.</p><p>I seek to diversify my talents, as much to learn more but also to understand everyone's needs and thus communicate better.</p>",
            "art3":"<h2>Languages I love</h2><div class='group'><img src='content/img/html5.svg' alt='html5 logo'><img src='content/img/css.svg' alt='css logo'><p>Impossible to miss for web development, although both seem simple on the surface, there is a lot to cover than just making a pretty page and SEO and optimization starts here.</p></div><div class='group'><p>Both in vanilal or with frameworks or NodeJS, I am able to adapt to be able to respond to your requests.</p><img src='content/img/js.svg' alt='javascript logo'></div><div class='group'><img src='content/img/php.svg' alt='php logo'><p>As a server language in vanilla, with Wordpress or anything else, PHP does not scare me.</p></div><div class='group'><p>Passionate about video games, I aim to create my own projects and have already acquired a lot of knowledge in hope to achieve this.</p><img src='content/img/csharp.svg' alt='c-sharp logo'><img src='content/img/unity.svg' alt='unity logo' class='unity-logo outline'></div><div class='group' id='projects'><p>+</p><p>And much more to mee your needs, learning does not scare me and is also a skill. I already had to work on projects in Go, ASP.Net, Visual Basic, Basic, Python, and many other languages.</p></div>",
            "my-projects":"My projects",
            "ongoing-text":"Ongoing",
            "finished-text":"Finished",
            "contact-me":"<h2>Contact me!</h2><div class='group'><div><p>Want to simply say \"Hello\" or hire me? Do not hesitate to contact me!</p><p>You can email me at my address: <a href='mailto:nresmi.pro@gmail.com'>nresmi.pro@gmail.com</a></p></div></div>"
        }
    },
    "multiple": {
        "fr": {
            "card": [
                "<img src='./content/img/img1.png' alt='Image of the code wrote'><h3>Favs</h3><div class='content'><p>Objectif que je m'étais déjà fixé étant plus petit, une page d'accueil personnalisable, actuellement toujours en développement mais la première version est déjà accessible avec les fonctionnalités les plus basiques disponibles.</p><p>Un projet qui paraît simple mais un code très lourd visant à être optimisé, aussi bien au niveau de sa longueur que du côté de votre navigateur. J'avais pour ambition de faire un site léger afin de m'opposer aux sites beaucoup trop lourds rien qu'à leur génération, qui est aujourd'hui un standard beaucoup trop présent.</p><p>Il a été fait avec du HTML/CSS et du Javascript vanilla (sans librairie). Pour la base de donnée, j'ai utilisé IndexedDB qui est une BDD sauvegardant les informations dans votre navigateur lui-même, il n'y a donc pas de coût de mon côté et quasiment aucun impact du votre étant donné que l'espace mémoire nécessaire est négligeable.</p><p>Cette première version était un assez gros challenge, et bien plus est à venir : système de pages, ajout de customisation des icônes, facilitation à modifier certaines parties du css...</p><ul class='list-square'><li>Créer une architecture de base de données (JSON à utilisation locale) et gérer son utilisation en fonction des actions utilisateurs</li><li>Création d'un outil avec pour objectif de le faire évoluer dans le temps</li><li>Création de l'architecture front et back et de leur optimisation en suivant le modèle de développement fonctionnel</li></ul></div><span>Lire plus...</span>",
                "<img src='./content/img/sepimo.png' alt='Map that can be found on the website'><h3>Sepimo</h3><div class='content'><p>Sepimo est un site développé avec Wordpress et un CRM fait maison afin d'offrir un moyen d'alimenter son contenu d'une autre façon pour le client.</p><p>J'ai dû ainsi permettre au client d'utiliser à la fois le CRM de WMKI et le CMS de Wordpress afin d'alimenter le site.</p><p>J'ai été confronté à la création d'une carte intéractive avec l'API de Google, et à la gestion de points d'intérêts provenant des diverses sources de contenu.</p><p>Cependant, l'API de Google n'est pas la seule carte disponible sur le site, et j'ai eu à permettre la recherche par région via une carte plus simple.</p><p>J'ai aussi eu à y dynamiser les articles disponibles pour chacun de ces points d'intérêts (et d'autres), ainsi que les articles de la partie \"actualités\", et j'ai aidé à la réparation d'une partie des simulateurs disponibles sur le site.</p><ul class='list-square'><li>Développement d'une carte avec l'API Google et placement de poiints d'intérêts</li><li>Gestion de la liaison entre le back-office Wordpress et un CRM custom pour faciliter la création de nouvelles pages</li><li>Création de plusieurs template de page</li><li>Implémentation et gestion de multiples plugin Wordpress</li><li>Mise à jour de plusieurs simulateur développés en ASP.Net</li></ul></div><span>Lire plus...</span>",
                "<img src='./content/img/nacarat.png' alt='Home of the website Nacarat'><h3>Nacarat</h3><div class='content'><p>Content de mes résultats, MKI m'a pris en freelance pour pouvoir aider au développement d'un nouveau projet.</p><p>J'ai eu à aider du côté de l'intégration et ai majoritairement aidé à la dynamisation du site, toujours avec les articles, et notamment avec la page glossaire.</p><ul class='list-square'><li>Gestion du contenu provenant du back-office Wordpress et d'un CRM custom</li><li>Création de fonction pour aider l'organisation lors de la création de nouveaux contenus</li><li>Optimisation du code front et back</li></ul></div><span>Lire plus...</span>"
            ]
        },
        "en": {
            "card": [
                "<img src='./content/img/img1.png' alt='Image of the code wrote'><h3>Favs</h3><div class='content'><p>Objective that I had already set myself when I was younger, a customizable homepage, currently still in development but the first version if already accessible with the most basic features available.</p><p>A project that seems simple but a very heavy code aimed at being optimized, both in terms of its length and on the side of your browser. My ambition was to make a light site in order to oppose the sites that were much too heavy even at their generation, which is today a standard that is far too present.</p><p>Made with HTML/CSS and vanilla Javascript (without library). For the database, I used IndexedDB which is a database saving the informations in your browser itself, so there is no cost on my side and close to no impact on yours given that the memory space required is negligible.</p><p>This first version was quite a big challenge, and much more is to come: page system, addition of customization of icons, facilitation to modify part of the CSS...</p><ul class='list-square'><li>Create a database architecture (JSON for local use) and manage its use based on user actions</li><li>Creation of a tool with the aim of making it evolve over time</li><li>Creation of the front and back architecture and their optimization following the functional development model pattern</li></ul></div><span>Read more...</span>",
                "<img src='./content/img/sepimo.png' alt='Map that can be found on the website'><h3>Sepimo</h3><div class='content'><p>Sepimo is a site developed with Wordpress and an in-house CRM to provide a way to feed its content in another way for the client.</p><p>So I had to allow them to use both the CRM of WMKI and the Wordpress CMS in order to feed the site.</p><p>I was faced with the creation of an interactive map with the Google API, and the management of points of interest from various content source.</p><p>However, Google's API is not the only map available on the site, and I had to allow searching by region via a simpler map.</p><p>I also had to dynamize the articles available for each of these points of interest (and more), as well as the articles in the \"new\" section, and I helped repair some of the simulators available on the site.</p><ul class='list-square'><li>Development of a map with the Google API and placement of points of interest</li><li>Management of the link between the Wordpress back-office and a custom CRM to facilitate the creation of new pages</li><li>Creation of several page templates</li><li>Implementation and management of multiple Wordpress plugins</li><li>Update of several simulators developed in ASP.Net</li></ul></div><span>Read more...</span>",
                "<img src='./content/img/nacarat.png' alt='Home of the website Nacarat'><h3>Nacarat</h3><div class='content'><p>Happy with my results, MKI took me on as a freelancer to help on the development of a new project.</p><p>I had to help on the integration side and mainly helped to dynamize the site, always with the articles, and in particular with the glossary page.</p><ul class='list-square'><li>Management of content from the Wordpress back-office and with the custom CRM</li><li>Created functions to help the organization of pages when creating new content</li><li>Front and back code optimization</li></ul></div><span>Read more...</span>"
            ]
        }
    }
}